package com.example.springAI.controller.structureoutputcontroller;

import com.example.springAI.Movie;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.converter.ListOutputConverter;
import org.springframework.ai.converter.MapOutputConverter;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.core.convert.support.DefaultConversionService;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.Map;

@RestController
public class AIController {

    ChatClient chatClient;

    public AIController(ChatClient.Builder chatClientBuilder) {
        this.chatClient = chatClientBuilder.build();
    }


    @GetMapping("/chat")
    public String getResponse(@RequestParam(value = "message", defaultValue = "Top 5 cities in India") String message) {
        return chatClient.prompt()
                .user(message) // sets the user message
                .call() // sends the request to the LLM
                .content();

        //         This is an old way not working   // this is a new way it is working
        //         getResult().getOutput() ==       .call().entity(MyType.class)

//                .chatResponse() //  is used when you need the full structured response, not just the text.
//                .getResult()// Extracts the actual result from the response, primary generated answer
//                .getOutput()// From the result, this pulls the model’s output object. Output may include: ,Text ,Tool calls ,Function calls ,Structured data
//                 content() - is used to get the final text response generated by the AI model.
//                 This is new method .content() —>  instead of getContent()


    }

    @GetMapping("/chatList")
    public List<String> getResponseAsList(@RequestParam(value = "message", defaultValue = "Top 5 cities in India") String message) {
        return chatClient.prompt()
                .user(message) // sets the user message
                .call() // sends the request to the LLM
                .entity(new ListOutputConverter(new DefaultConversionService()));
    }


    @GetMapping("/chatMap")
    public Map<String, Object> getResponseAsMap(@RequestParam(value = "message", defaultValue = "How to become 0.01% JAVA Computer Science Developer") String message) {
        return chatClient.prompt()
                .system("Return ONLY valid JSON. No explanations. No markdown.")
                .user(message)

                .call()
                .entity(new MapOutputConverter()); // When I use this then it is working
               // .entity(new ParameterizedTypeReference<Map<String, String>>() {});

        // ParameterizedTypeReference : is a container for generic type info.
        // MapOutputConverter is an OutputConverter used by Spring AI -> Convert LLM text output into a Map<String, Object> <- Map can be dynamic .

    }

    @GetMapping("/director-movie-service")
    public List<Movie> getDirectorMovies(@RequestParam("directorName") String directorName) {
        String template = """  
                "Generate a list of movies directed by {directorName}. If the director is unknow, return null .
                Each movie should include a tittle and release year. {format}" """;

        List<Movie> movieList = chatClient.prompt()
                .user(userSpec -> userSpec.text(template)
                        // sets the message content
                        // userSpec.text(template)template is the prompt text (your triple-quoted string)
                        // It only sets the text that will be processed later.
                        .param("directorName", directorName)
                        // .param() → replaces {{variable}} in prompt text
                        // Used only with templates, Mandotory when placeholder exist
                        .param("format", "json")) // here i am changing format into JSON format .

                .call()// execute the AI request . in simple term This is  Trigger Point
                .entity(new ParameterizedTypeReference<List<Movie>>() {
                });
        // entity() - converts the LLM response into a Java object.
        // new ParameterizedTypeReference<List<Movie>>() - exists only because Java forgets generics .
        // it restores them so Spring can deserialize correctly.
        return movieList;
    }


}
