spring.application.name=mcp-server
spring.main.web-application-type=none
spring.ai.mcp.server.name=author-mcp-server
spring.main.banner-mode=off
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.stdio=true

logging.level.root=OFF
logging.console.target=OFF
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
