package com.example.springAI.controller.structureoutputController_2;

import com.example.springAI.Movie;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.converter.ListOutputConverter;
import org.springframework.ai.converter.MapOutputConverter;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.core.convert.support.DefaultConversionService;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.lang.reflect.Type;
import java.util.List;
import java.util.Map;

@RestController
public class AIController {

    ChatClient chatClient;

    public AIController(ChatClient.Builder chatClientBuilder) {
        this.chatClient = chatClientBuilder.build();
    }


    @GetMapping("/chat")
    public String getResponse(@RequestParam(value = "message", defaultValue = "Top 5 cities in India") String message) {
        return chatClient.prompt()
                .user(message) // sets the user message
                .call() // sends the request to the LLM
                .content();

        // this is a old way not working   // this is new way it is working
        //  getResult().getOutput() == .call().entity(MyType.class)

//                .chatResponse() // Returns the full response object from the chat API.
//                .getResult()// Extracts the actual result from the response, primary generated answer
//                .getOutput()// From the result, this pulls the model’s output object. Output may include: ,Text ,Tool calls ,Function calls ,Structured data
// THis method is new one .content(); // this is the latest method instead of getContent()
        // content() - is used to get the final text response generated by the AI model.


    }

    @GetMapping("/chatList")
    public List<String> getResponseAsList(@RequestParam(value = "message", defaultValue = "Top 5 cities in India") String message) {
        return chatClient.prompt()
                .user(message) // sets the user message
                .call() // sends the request to the LLM
                .entity(new ListOutputConverter(new DefaultConversionService()));
    }


    // this is working with wrong result
    @GetMapping("/chatMap")
    public Map<String, String> getResponseAsMap(@RequestParam(value = "message", defaultValue = "Top 5 cities in India") String message) {
        return chatClient.prompt()
                .user(message)
                .call()
                //.entity(new ParameterizedTypeReference<Map<String, String>>() {});
                .entity(new ParameterizedTypeReference<Map<String, String>>() {
                });
    }

    @GetMapping("/director-movie-service")
    public List<Movie> getDirectorMovies(@RequestParam("directorName") String directorName) {
        String template = """  
                "Generate a list of movies directed by {directorName}. If the director is unknow, return null .
                Each movie should include a tittle and release year. {format}" """;

        List<Movie> movieList = chatClient.prompt()
                .user(userSpec -> userSpec.text(template)
                        // sets the message content
                        // userSpec.text(template)template is the prompt text (your triple-quoted string)
                        // It only sets the text that will be processed later.
                        .param("directorName", directorName)
                        // .param() → replaces {{variable}} in prompt text
                        // Used only with templates, Mandotory when placeholder exist
                        .param("format", "json")) // here i am changing format into JSON format .

                .call()// execute the AI request . in simple term This is  Trigger Point
                .entity(new ParameterizedTypeReference<List<Movie>>() {
                });
        // entity() - converts the LLM response into a Java object.
        // new ParameterizedTypeReference<List<Movie>>() - exists only because Java forgets generics .
        // it restores them so Spring can deserialize correctly.

        return movieList;
    }


}
